name: check lint and format
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv sync
          pipenv sync --dev --python $(which python)
          pipenv shell --fancy --python $(which python)
          pipenv install -r web-app/requirements.txt
      - name: Lint with pylint
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          pipenv run pylint **/*.py -d C,R,I,W
      - name: Format with black
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          pipenc run black .
          pipenv run black --diff --check .
